# Generated by Django 4.0.3 on 2023-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50, unique=True)),
                ('service_id', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('alert_ts', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=100)),
                ('team_slack', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('alert_ts', 'alert_id'),
            },
        ),
    ]
